//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loft
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdProduct { get; set; }
        public int IdEmployee { get; set; }
        public string Date { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual EmployeeSet EmployeeSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
