//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loft
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSet
    {
        public int Id { get; set; }
        public string Colour { get; set; }
        public string Size { get; set; }
        public string Quantity { get; set; }
        public string Material { get; set; }
        public Nullable<long> Price { get; set; }
    }
}
